### ISSUE TITLE
As a single player, I can access the MULTIWORDLE website and see an informative page

### ISSUE THREAD

**Issue by benpalay** [witseie-elen4010/2022-group-lab-001#44]
#45
Acceptance Tests: The user can access the deployed website via http://multiwordle.azurewebsites.net/.

**Comment by IlanMalk** [comment]
# Acceptance Criteria
- [ ] Webpage is accessible via URL
- [ ] Heading is Multiwordle

# Acceptance Tests
- [ ] Enter the website URL and ensure you see the title `Multiwordle`

# Notes
- [ ] Confirm he webpage is hosted on Azure
- [ ] Continuous integration should be set up: add a subtitile `The competitive word guessing game` and push it to the repo. Ensure the change reflects on the site

**Comment by RyanSelesnik** [comment]
Note: this story doesn't have an associated pull request since this was the initial commit
