### ISSUE TITLE
As a single player, I can access a log of the game's actions taken 

### ISSUE THREAD

**Issue by benpalay** [witseie-elen4010/2022-group-lab-001#72]
**Acceptance tests**

1. As a user, I must be able to access a log from the website which shows all actions taken by all players. 

2. Each entry in the log should contain the
date and time of the action, the nature of the action, and identify the player who
initiated the action

3. All the logs should be displayed, i.e logs from previous days

**Comment by IlanMalk** [comment]
Note: this functionality is updated in #98. After #98 players can only see their own guesses
